CREATE DATABASE BancoJavaProva;
USE BancoJavaProva;

CREATE TABLE IF NOT EXISTS chef (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    dataNascimento DATE NOT NULL,
    especialidade VARCHAR(45) NOT NULL,
    salario VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
)
ENGINE = InnoDB;

SELECT * FROM chef;

CREATE TABLE IF NOT EXISTS cliente (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
	dataNascimento DATE NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
)
ENGINE = InnoDB;

SELECT * FROM cliente;